{
 "title": "Aquarium monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AQUARIUM_INSTANCE",
    "label": "Aquarium instance ID",
    "query": {
     "query": "label_values(aquarium_process_start_time_seconds,exported_instance)"
    }
   },
   {
    "name": "DOMAIN",
    "label": "Domain job",
    "query": {
     "query": "label_values(aquarium_process_start_time_seconds{exported_instance=\"$AQUARIUM_INSTANCE\"},scrape_job)"
    }
   },
   {
    "name": "VERSION",
    "label": "Version",
    "query": {
     "query": "label_values(aquarium_process_start_time_seconds{exported_instance=\"$AQUARIUM_INSTANCE\"},version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "# Domain: **${DOMAIN}**\n## Version: **${VERSION}**"
   }
  },
  {
   "title": "Last restart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "aquarium_process_start_time_seconds{exported_instance=\"$AQUARIUM_INSTANCE\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database requests per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "aquarium_database_request_per_seconds{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database success rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((aquarium_database_request_count{exported_instance=\"$AQUARIUM_INSTANCE\"} - aquarium_database_failed_request_count{exported_instance=\"$AQUARIUM_INSTANCE\"}) / aquarium_database_request_count{exported_instance=\"$AQUARIUM_INSTANCE\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database request count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aquarium_database_request_count{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aquarium_request_count{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "Usage is express as a %",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aquarium_process_cpu_usage_percentage{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (heap)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aquarium_process_used_heap_bytes{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aquarium_process_used_heap_bytes{exported_instance=\"$AQUARIUM_INSTANCE\"} / aquarium_process_heap_bytes{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (resident)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aquarium_process_resident_memory_bytes{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websockets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "aquarium_wss_request_count{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aquarium_wss_request_per_seconds{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FFprobe and FFmpeg processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "aquarium_ffprobe_processes{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aquarium_ffmpeg_processes{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of events in queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "aquarium_queue_queries_jobs{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "aquarium_queue_clear_old_events_jobs{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "aquarium_queue_evaluate_events_jobs{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "aquarium_queue_evaluate_timers_jobs{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "aquarium_queue_file_processes_jobs{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "aquarium_all_queues_jobs{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log length",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aquarium_log_length{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of open files by process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "aquarium_process_open_fds{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of open tracked sent files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "aquarium_open_tracked_files_count{exported_instance=\"$AQUARIUM_INSTANCE\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}